### ISSUE TITLE
Homey 2.0 - Flow statement - "Then" issue

### ISSUE THREAD

**Issue by daan256** [scanno/nl.scanno.mqtt#16]
Hi, 
Thanks for this great app.

I have a flow:

If: something xxx
And: something xxx
Then: Send MQQT message

The MQQT message is **not** sent:

If: Something xxx
And: empty
Then: Send MQQT message 

This does work and the MQQT message is sent.

Any ideas?
I am on the beta MQQT app of the latest stable Homey 2.0 version.

**Comment by scanno** [comment]
Please get some logging from the settings page.

**Comment by daan256** [comment]
it seemed to fail when executing the "test" flow.
Now working again.
No biggy.

Thanks for your response.
