### ISSUE TITLE
Owntracks or MQTT Client

### ISSUE THREAD

**Issue by FrankRinkens** [scanno/nl.scanno.mqtt#17]
Hi 

I'm using Owntracks client succesfully for a long time with the Owntracks app that changes name to "Lokatie en Aanwezigheid" I use CloudMQTT as a broker.

Now I want to use (test) MQTT Gateway and I see this one is using MQTT Client. Should I now remove Lokatie en aanwezigheid or should this one run next to the MQTT Client? (with same settings.

I'm a bit puzzled now.

**Comment by scanno** [comment]
You can have them running together using the same settings. But you can ofc make a new account for the mqtt client on the broker.

**Comment by FrankRinkens** [comment]
ok thx. I thought maybe the gateway could also talk to the "lokatie en aanwezigheid" app as the MQTT client as this is already configured there. Than installing of the MQTT client wasn't nescessary.
