### ISSUE TITLE
[feature request] Add retain and QoS options to publish card

### ISSUE THREAD

**Issue by acefed** [scanno/nl.scanno.mqtt#2]
Wouldn't it be great to have the option to be able to publish retained messages?

Not sure if it's possible, but adding a checkbox on the publish card (default unchecked, do not retain) would be a very user friendly way of implementing this.

To a lesser degree the same goes for setting the QoS level, which could be achieved with a small selectbox (dropdown). Not sure if cards allow the possibility to code this.

PS: Many thanks for delivering the already most useful Homey app :)

**Comment by scanno** [comment]
Something like this ?

![checkbox2](https://user-images.githubusercontent.com/637981/29535875-e4c9d8ac-86bb-11e7-959b-2395dacef080.png)

**Comment by scanno** [comment]
Version 2.0.0 submitted to the beta channel. Above card is added as an extra card with QoS and retain

**Comment by acefed** [comment]
Wowzers, that's EXACTLY what I was looking for :)
I hoped to see some possible improvement within a few months, certainly didn't expect all fully featured options available within ONE day...
Looking forward to put these cards into action!

**Comment by scanno** [comment]
Published as beta in app store

**Comment by acefed** [comment]
Tnx!
