### ISSUE TITLE
Issue with Homey to send messages

### ISSUE THREAD

**Issue by pettib** [scanno/nl.scanno.mqtt#22]
Hi
I have been using Mqtt Client by Menno van Grinsven for a long time, at the moment i´m using latest version v2.2.2 - 25.02.19.
A few days ago Homey stopped sending messages. I can see that i tries to send but nothing been sent to the broker. 

The broker is working fine from other systems so I don´t think the problem is there.

When i look in the logfile in the app on Homey it shows MQTT Closed and Broker State Disconnected every second.

I have tried to update the username and password, change the Client ID.
Restart the App
Restart Homey
But nothing works.
I have many flows depending on mqtt so this is a big problem for at least me.
Is there anyone that have seen this before or know how to solve it, please respond.

regards Peter

**Comment by scanno** [comment]
Since the MQTT client has not changed for a while, what else has changed?
If you are using the Mqtt Gateway app, try restarting that one. 
What does the log on the mqtt broker say? Is there an incoming connection from the mqtt client? If so what does that log say about the reason why the connection is dropped? 

What MQTT broker are you using? 

Did you try rebooting your router and modem?

**Comment by pettib** [comment]
I know that it´s still the same version but still it´s not working and all my other mqtt client are working and I haven´t done any changes for several month. I have tried everything i can figure out beside of uninstall the app and reinstall. I´m not sure if I have to reconfig all my flows if I do so. 
I don´t think there are any problem with the app it self, just wondering if there can be any type of compatibility problem with some other app. 
Everything else is working besides of sending mqtt.
I can send a bug report from the app but the developer needs to look at it. I can´t read it my self. What I know. Please tell me if there is a way that I can read it my self.

**Comment by scanno** [comment]
The data that is send just contains the log that you can also see inside the settings. 
I would need to see the logs from the broker.
You have not answered the questions I asked you in my previous message. I cannot say anything besides the fact that the mqtt app cannot connect to or gets disconnected from the broker.
Without knowing what broker you are using and without logs from the broker to see if the client app gets connected and ant reasons why it gets connected nobody can really help.

You could try adding  a new flow that uses the send flow card and see if that works.

If you want any help, then provide information that can be of use to analyze the problem. You are not giving any useful info.
