### ISSUE TITLE
MQTT broker is Unavailable and 5 sec later is Availible again

### ISSUE THREAD

**Issue by Quart666** [scanno/nl.scanno.mqtt#24]
Maybe my setup is wrong but I got a lot of errors in my log on Homey about this.
Have my Mosquitto broker on the same Lan and in the same switch so its no connection problem.

**Comment by scanno** [comment]
The WiFi connection of Homey is too unstable. If I connect the MQTT client to my mosquitto server in my own network or an external broker, I have the same. If I connect the client to the MQTT broker on Homey (so local host) no disconnect problems.

The only conclusion I can make is that Homey cannot keep the connection alive. You Could try increasing the timeout value in the MQTT client settings to see if that solved the issue. Or disable receiving notifications from the MQTT client app.

The fact that the connection is stable when using the broker on Homey, supports the conclusion that homeys network connection is unstable.
