### ISSUE TITLE
[Feature request] "Last will" and "Birth" messages (plus "keep alive time" settings

### ISSUE THREAD

**Issue by CoonHouse** [scanno/nl.scanno.mqtt#7]
Hello Scanno,
First thank you for sharing this app. It's working great.

Would it be possible to implement  "Last will" and "Birth" messages in the "Client setup"? And while you'r on it maybe also a "keep alive time" setting?

Thanks and best regards,

Wilco

**Comment by scanno** [comment]
Will have a look at it. Dont know about the birth message though

**Comment by scanno** [comment]
Is implemented.

**Comment by CoonHouse** [comment]
Thanks!!

**Comment by scanno** [comment]
Only LWT. Could not find out birth. Topic is {clientid} /status
