### ISSUE TITLE
[Feature request] Allow publishing of null messages

### ISSUE THREAD

**Issue by acefed** [scanno/nl.scanno.mqtt#8]
Publishing an empty (null or zero byte payload) message to a topic is used by MQTT to remove a retained message from that topic. Currently, the publish card does not allow this. It would be great if this option was available also.

PS: Kudos for this awesome app, it rox!

**Comment by scanno** [comment]
It is not possible to have an empty text field, so it would either be an extra dropdown menu or an extra action card.

**Comment by acefed** [comment]
That's a bummer. In that case, I would opt for a new card if possible, without a message text field. This way, there's no impact on the existing cards/flows/users. I assume the retain option is also unused for empty messages, which could also be removed from a new null message card.

**Comment by harriedegroot** [comment]
Functionality is added in version 3.0.0
